name: bs
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prerequisites
        run: |
          sudo apt-get install pipx
          pipx install bikeshed
      - name: render
        run: |
          cd src
          for f in *.bs; do bikeshed spec $f; done
      - name: upload renders
        run: |
          message=$(git show -s --format=%s)
          mkdir /tmp/renders
          mv -v src/*.html /tmp/renders
          git checkout gh-pages
          mv -v /tmp/renders/* src
          rm -rfv drafts
          git checkout main -- drafts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "[Bikeshed]: $message"
          git push
