name: bs
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prerequisites
        run: |
          sudo apt-get install pipx
          pipx install bikeshed
      - name: render
        run: |
          changes=$(git diff --name-only HEAD HEAD~1 | grep src/ | cat)
          cd src
          for f in *.bs;
          do
            if [[ $changes =~ "src/$f" ]];
            then
              bikeshed spec $f
            fi
          done
      - name: upload renders
        run: |
          message=$(git show -s --format=%s)
          mkdir /tmp/renders
          if compgen -G "src/*.html" > /dev/null; then
            mv -v src/*.html /tmp/renders
          fi
          git checkout gh-pages
          if compgen -G "/tmp/renders/*" > /dev/null; then
            mv -v /tmp/renders/* src
          fi
          rm -rfv drafts
          git checkout main -- drafts
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -n "$(git status -s)" ]];
          then
            git commit -am "[Bikeshed]: $message"
            git push
          fi
